services:
  - type: web
    name: odoo-app
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    envVars:
      - key: 00_UGST
        value: dpg-dirlkvdw438x73af0w7g-a
      - key: 00_UGST_PORT
        value: "4433"
      - key: 00_USER
        value: odoo_app_user
      - key: 00_PASSWORD
        value: abode3WYnacG9b1fpp7zamqdQQgjvAP
      - key: 00_AUME
        value: odoo_app
      - key: 00_TILTER
        value: "odoo_app"