services:
  - type: web
    name: odoo
    env: docker
    dockerfilePath: ""  # optional if using prebuilt image
    image: odoo:17
    plan: standard
    autoDeploy: true
    dependsOn:
      - odoo-db
    envVars:
      - key: HOST
        value: 0.0.0.0
    ports:
      - 8069
    disks:
      - name: odoo-web-data
        mountPath: /var/lib/odoo
    volumeMounts:
      - path: /mnt/extra-addons
        name: addons
    buildCommand: ""
    startCommand: ""

  - type: pserv
    name: odoo-db
    env: docker
    image: postgres:15
    plan: starter
    autoDeploy: false
    envVars:
      - key: POSTGRES_DB
        value: myodoo
      - key: POSTGRES_USER
        value: odoo
      - key: POSTGRES_PASSWORD
        value: odoo
    disks:
      - name: odoo-db-data
        mountPath: /var/lib/postgresql/data

volumes:
  - name: odoo-db-data
    sizeGB: 1
  - name: odoo-web-data
    sizeGB: 1
  - name: addons
    sizeGB: 1
