services:
  - type: web
    name: odoo-app
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    envVars:
      - key: HOST
        value: dpg-dirlkvdw438x73af0w7g-a
      - key: PORT
        value: "5432" 
      - key: USER
        value: odoo_app_user
      - key: PASSWORD
        value: abode3WYnacG9b1fpp7zamqdQQgjvAP
      - key: DB_NAME
        value: odoo_app
      - key: ADMIN_PASSWD
        value: admin  
    ports:
      - port: 8069
    healthCheckPath: /web/health