services:
  - type: web
    name: odoo-app
    env: docker
    plan: standard
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DB_HOST
        value: dpg-d1rlkr6r433s73afuo7g-a
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        value: odoo_app_user
      - key: DB_PASSWORD
        value: a0o4bJNYaoeO5b1Kpp7zzmrq8CQNjrWP
      - key: DB_NAME
        value: odoo_app
      - key: DB_FILTER
        value: "^odoo_app$"
    ports:
      - port: 8069
