services:
  - type: web                      
    name: odoo-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: standard
    envVars:
      - key: DB_HOST
        value: postgresql://odoo_app_user:a0o4bJNYaoeO5b1Kpp7zzmrq8CQNjrWP@dpg-d1rlkr6r433s73afuo7g-a/odoo_app    
      - key: DB_PORT
        value: "5432"
      - key: DB_USER
        value: odoo
      - key: DB_PASSWORD
        value: odoo
      - key: DB_NAME
        value: myodoo
      - key: DB_FILTER
        value: "^myodoo$"
    ports:
      - port: 8069                 
